import { Component, Input, OnInit } from '@angular/core';
import { Song } from 'src/app/models/song';

@Component({
  selector: 'app-playlist',
  templateUrl: './playlist.component.html',
  styleUrls: ['./playlist.component.scss']
})
export class PlaylistComponent implements OnInit {
  songs!: Song[]


  ngOnInit(): void {
    this.songs = [
      {
        "id": 2,
        "songSinger": "Edward Sanda X Theo Rose",
        "songName": "Stii unde ma gasesti",
        "songLikes": 0,
        "songDislikes": 0,
        "youtubeId": "9APbLzu5ZRQ",
        "dateRadioPlayed": "17-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "NANE",
        "songName": "COCKTAIL",
        "songLikes": 1,
        "songDislikes": 0,
        "youtubeId": "6d8LU2Mu_Y4",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      },
      {
        "id": 3,
        "songSinger": "KILLA FONIC",
        "songName": "Miami Bici",
        "songLikes": 0,
        "songDislikes": 1,
        "youtubeId": "7XQ0t89ibJw",
        "dateRadioPlayed": "16-09-2023 15:12:33",
        "radioChannel": "KissFM",
      }
    ]
  }
}
